const get=(req,res)=>{
    res.send([
        {
            id:null,
        name:"The Indian Express",
        author:null,
        title:"Pathaan box office Day 12: Shah Rukh Khan film earns Rs 832.2 cr globally, to surpass RRR’s US collection - The Indian Express",
        description:null,
        urlToImage:"https://images.prothomalo.com/prothomalo-english%2F2022-12%2F5d23ea3b-c89e-4b28-9f73-91671e1f163b%2FIMG_20221222_221630.jpg?rect=0%2C0%2C900%2C506&auto=format%2Ccompress&fmt=webp&format=webp&w=480&dpr=2.6",
        url:"https://indianexpress.com/article/entertainment/bollywood/pathaan-box-office-day-12-srk-rs-900-crore-worldwide-beats-ss-rajamouli-rrr-us-record-8426245",
        publishedAt:"2023-02-06T08:12:21Z",
        content:"Hermes is a Greek Olympian, god. Born to Zeus and Maya, Hermes is known for his quick thinking and cunning nature. He is the youngest of the Olympians and known for moving quickly between the divine and mortal worlds. Because of this power, Hermes often acted as a messenger between the men and the Olympians. A benevolent god, Hermes protects travellers and athletes. He is also known as mischievous as he often plays tricks on other gods. He does this for his own amusement or to save people from the wrath of the gods. Hermes is also the fastest of all the gods because he has wings with his sandals. Interestingly, even when Hermes was a child he could not resist the urge to steal. Therefore, he is also credited as the patron god of all thieves.Atoms of radioactive elements can split. According to Albert Einstein, mass and energy are interchangeable under certain circumstances. When atoms split, the process is called nuclear fission. In this case, a small amount of mass is converted into energy. Thus the energy released cannot do much damage. However, several subatomic particles called neutrons are also emitted during this process. Each neutron will hit a radioactive element releasing more neutrons in the process. This causes a chain reaction and creates a large amount of energy. This energy is converted into heat which expands uncontrollably causing an explosion. Hence, atoms do not literally explode. They generate energy that can cause explosions."
        },
        
        {id:"the-times-of-india",
        name:"The Times of India",
        author:null,
        title:"Video of Sara Ali Khan avoiding paparazzi and running inside a building goes viral; netizens drop hilarious comments: Bhaag bhaag, 'Shubman Gill ko leke wo bhaag jaayegi warna' - Indiatimes.com",
        description:"Sara Ali Khan is known for her welcoming nature and warm personality. The diva, who always greets the paparazzi with her signature namaste and big smile, recently spotted running away from the shutterbugs. A video surfaced on social media where Sara can be se…",
        url:"https://timesofindia.indiatimes.com/videos/entertainment/hindi/video-of-sara-ali-khan-avoiding-paparazzi-and-running-inside-a-building-goes-viral-netizens-drop-hilarious-comments-bhaag-bhaag-shubman-gill-ko-leke-wo-bhaag-jaayegi-warna/videoshow/97640213.cms",
        urlToImage:"https://timesofindia.indiatimes.com/photo/97640213/size-58490/97640213.jpg",
        publishedAt:"2023-02-06T07:26:39Z",
        content:"Sara Ali Khan\r\n is known for her welcoming nature and warm personality. The diva, who always greets the paparazzi with her signature namaste and big smile, recently spotted running away from the shut… [+457 chars]. Everyone knows that paper is made from trees. But when one looks at trees, one cannot imagine that something so soft and fragile as the paper is made is so hard and strong. Plant materials such as wood are made of fibres known as cellulose. It is the primary ingredient in paper making. Raw wood is first converted into pulp consisting of a mixture of Cellulose, lignin, water and some chemicals. The pulp can be made mechanically through grinders or through chemical processes. Short fibres are produced by mechanical grinding. The paper produced in this way is weak and is used to make newspapers, magazines and phonebooks. Through the chemical pulping process, strong paper is produced. Cellulose pulp is sprayed to form mats on moving conveyor screens. These mats are then dried, dyed and cut as required.You probably already know that it is important to have a king-size breakfast every morning. do you know why Your body is hungry in the morning because you haven’t eaten for about 8-10 hours? Breakfast is therefore the first meal of the day, and therefore, the most important. Imagine driving without fuel; This is exactly how your body feels without fuel from a nutritious breakfast. Nowadays many people skip breakfast to lose weight. Nutritionists are alarmed by this trend, as it is mandatory to eat breakfast within two hours of waking up. Depriving the body of energy can lead to serious health problems in the long run. Forget silly celebrities and their absurd ways to lose weight. Never miss breakfast!"
        },
        
        {
            id:null,
        name:"Koimoi",
        author:"Jishika Madaan",
        title:"Pathaan Box Office Day 13 Morning Occupancy: Playing In Single-Digit, All Eyes Set On Evening & Night Shows - Koimoi",
        description:"Pathaan is witnessing single a drop at the ticket windows as far as the morning occupancy on Day 13 is concerned but nothing to worry about!",
        url:"https://www.koimoi.com/?p=959331",
        urlToImage:"https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/02/pathaan-box-office-day-13-morning-occupancy-playing-in-single-digit-after-coming-from-a-blockbuster-sunday-001.jpg",
        publishedAt:"2023-02-06T07:04:27Z",
        content:"Pathaan Box Office Day 13 Morning Occupancy Updates!(Photo Credit Still From Pathaan)\r\nPathaan Box Office Day 13 Morning Occupancy: It is too good to be true, for a Bollywood film to shine this brigh… [+1907 chars].Positive thinking is an attitude or mindset characterized by optimism and happiness. A positive person hopes for the best and expects success in his life. Although many may scoff at the idea of ​​staying positive all the time, it has a plethora of benefits not only for the mind but also for the body. Positivity brings happiness to the soul and lightens one. It evokes our goodwill and joy. People are attracted to such people. One sword and being negative inaction causes the exact opposite reaction. It is a known fact that people try to avoid people who exude negativity. They don’t want to be around someone who brings down the energy in the house. Positive feedback to yourself can improve your health and increase your chances of success in life. It is recommended that one refrain from using harsh words in their thoughts or words. Be kind and gentle to yourself, encouraging and comforting. Only then can one achieve everything he wants in life.The teacher of today is the salt of the earth. He wants to create a man, not just make money. He is a knowledgeable gentleman. He is an expert in the particular subject he teaches. Though a scholar, he teaches the subject in such a way that all students, brilliant or ordinary, can fully understand him. He doesn’t advertise his knowledge. He cares about his students and offers assistance to them both inside and outside of the classroom. He attends his work regularly.Anything that seems untidy gets the side eye from him. Being conscious of his social responsibilities, he offers assistance to neighbours in need and spends his free time on social services. But there are very few teachers who consider teaching as a mere profession like any other profession. They do not have the dedication to become great teachers for ages."
        },
        
        {
            id:null,
            name:"Hindustan Times",
            author:"HT Entertainment Desk",
            title:"Kangana warns Bollywood couple that 'spied' on her: 'Sudhar jao nahi toh...' - Hindustan Times",
            description:"Actor Kangana Ranaut alleged that a popular Bollywood couple was 'spying' on her. A day later, the actor took to Instagram to warn the 'Casanova' and his wife to mend their ways, or else she will teach them a lesson, saying people who call her 'pagal (mad)', …",
            url:"https://www.hindustantimes.com/entertainment/bollywood/kangana-ranaut-warns-bollywood-couple-that-spied-on-her-sudhar-jao-nahi-toh-ghar-mein-ghoos-ke-marungi-101675664855155.html",
            urlToImage:"https://images.hindustantimes.com/img/2023/02/06/1600x900/kangana_ranaut_1674625924215_1675665557465_1675665557465.jpg",
            publishedAt:"2023-02-06T07:03:32Z",
            content:"On Sunday, actor Kangana Ranaut took to Instagram Stories and spoke about a Bollywood couple that was 'spying' on her. She did not take any names, but Reddit users were convinced that Kangana was spe… [+4342 chars].The Dowry system is bad in society. It has turned the sacred matter of marriage into a business deal. The bride is regarded as a marketable commodity. Bride’s parents are often put under inhumane pressure for a handsome dowry. Sometimes they become destitute to give their daughters in marriage. In many cases, young brides are brutally tortured or pushed to commit suicide.To eliminate this social evil, a complete change in society’s outlook is necessary. Women should be treated as equal partners to men. Their right to comprehensive education and employment and property can bring the right remedy. Legal prohibition of dowry is not enough. Strict social disapproval of dowry is the only guarantee against this evil. Our youth should come forward to create public awareness against this shameful practice. Training in a specific branch of applied science, such as engineering, agriculture, weaving, spinning, etc., is considered technical education. It contrasts with liberal education which aims to impart general knowledge of arts and sciences. In the modern era, technical education is extremely important. Today, a country’s prosperity is determined by its industrial development. The more advanced the country is in industry, the more prosperous the country is. Technical knowledge is now the backbone of industrial progress, which holds the key to national prosperity.The need for technical education in India is high. The Central Government has made major efforts to build heavy industry since independence. People trained in technical education are required to run various industrial units. Technical education offers a student good prospects. Today, engineering graduates are more likely to find jobs than science or arts graduates. "
        },
        
        {
        id:null,
        name:"Koimoi",
        author:"Shalmesh More",
        title:"Pathaan Box Office: Siddharth Anand Beats SS Rajamouli, Ali Abbas Zafar & Rajkumar Hirani To Grab 2nd Spot In Directors’ Power Index! - Koimoi",
        description:"Even Siddharth Anand deserves equal applause for Pathaan & here, at Koimoi's Directors' Power Index, we have just done that. Read on!",
        url:"https://www.koimoi.com/box-office/pathaan-box-office-siddharth-anand-beats-ss-rajamouli-ali-abbas-zafar-rajkumar-hirani-to-grab-2nd-spot-in-directors-power-index/",
        urlToImage:"https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/02/with-pathaan-siddharth-anand-becomes-no-2-in-directors-power-index-001.jpg",
        publishedAt:"2023-02-06T06:49:18Z",
        content:"Siddharth Anand Make Huge Gains With Pathaan(Photo Credit Instagram/Poster From Pathaan/YRF/Youtube)\r\nIt’s a wave of joy all across Bollywood as Pathaan destroying box office records has given a much… [+1823 chars].There are many children in our country who are deprived of education and the normal joyous experiences of childhood. While upper-middle-class boys and girls attend school, they work in tea shops or small factories. They work as servants in middle-class and upper-class households. Parents are very poor, so children are forced to take up all these occupations.Government should come up with strict laws to solve this problem. Along with the law, the government should introduce some economic reforms which will bring down the poverty line to some extent. Apart from this, to solve this problem, illiteracy needs to be eliminated and the birth rate must be controlled.Mr Bucket was the only person in the family with a job. He worked in a toothpaste factory, where he sat all day long on a bench and screwed the little caps onto the tops of the tubes of toothpaste after the tubes had been filled. But a toothpaste cap-screwer is never paid very much money, and poor Mr Bucket, however hard he worked, and however fast he screwed on the caps, was never able to make enough to buy one-half of the things that so large a family needed. There wasn’t even enough money to buy proper food for them all. The only meals they could afford were bread and margarine for breakfast, boiled potatoes and cabbage for lunch, and cabbage soup for supper. Sundays were a bit better. They all looked forward to Sundays because then, although they had exactly the same, everyone was allowed a second helping."
        },
        
        
        {
            id:null,
            name:"PINKVILLA",
            author:"Jatinder Singh",
            title:"Varisu box office collections; Emerges highest grossing film for Vijay, Crosses Rs. 300 crores worldwide - PINKVILLA",
            description:"This Makes It The Highest-grossing Film For Vijay In India, Beating His Previous Best Master. The Film Has Grossed Another $10.80 Million Overseas, For A Worldwide Gross Of Rs. 302 Crores.",
            url:"https://www.pinkvilla.com/entertainment/box-office/varisu-box-office-collections-emerges-highest-grossing-film-for-vijay-crosses-rs-300-crores-worldwide-1208286",
            urlToImage:"https://www.pinkvilla.com/english/images/2022/12/484397485_thalapathy-vijay-varisu-release-date_1280*720.jpg",
            publishedAt:"2023-02-06T06:22:13Z",
            content:"Varisu had another good weekend at the box office, adding Rs. 3.25 crores, which takes its all-India total to Rs. 214 crores approx. This makes it the highest-grossing film for Vijay in India, beatin… [+1908 chars].Generating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. The writer has no idea what topic the random paragraph will be about when it appears. This forces the writer to use creativity to complete one of three common writing challenges. The writer can use the paragraph as the first one of a short story and build upon it. A second option is to use the random paragraph somewhere in a short story they create. The third option is to have the random paragraph be the ending paragraph in a short story. No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing.If you're looking for random paragraphs, you've come to the right place. When a random word or a random sentence isn't quite enough, the next logical step is to find a random paragraph. We created the Random Paragraph Generator with you in mind. The process is quite simple. Choose the number of random paragraphs you'd like to see and click the button. Your chosen number of paragraphs will instantly appear. While it may not be obvious to everyone, there are a number of reasons creating random paragraphs can be useful. A few examples of how some people use this generator are listed in the following paragraphs."
        },
        
        {
            id:null,
            name:"Hindustan Times",
            author:"HT Entertainment Desk",
            title:"Sidharth Malhotra-Kiara Advani wedding live updates: Their only vacay pic - Hindustan Times",
            description:"Sidharth Kiara wedding live updates: Kiara Advani's childhood friend Isha Ambani reached Jaisalmer for her wedding celebrations.",
            url:"https://www.hindustantimes.com/entertainment/bollywood/sidharth-malhotra-kiara-advani-wedding-live-updates-isha-ambani-reaches-venue-101675647686320.html",
            urlToImage:"https://images.hindustantimes.com/img/2023/02/06/1600x900/sidharth_malhotra_kiara_advani_wedding_1675656531390_1675656531645_1675656531645.jpg",
            publishedAt:"2023-02-06T04:22:56Z",
            content:"Here's a sneak peek into Jaisalmer's Suryagarh Palace\r\nKiara Advani and Sidharth Malhotra's wedding venue, Suryagarh Palace in Jaisalmer, is entirely booked from February 4-11. It boasts of picturesq… [+58 chars].Another writing challenge can be to take the individual sentences in the random paragraph and incorporate a single sentence from that into a new paragraph to create a short story. Unlike the random sentence generator, the sentences from the random paragraph will have some connection to one another so it will be a bit different. You also won't know exactly how many sentences will appear in the random paragraph. It's not only writers who can benefit from this free online tool. If you're a programmer who's working on a project where blocks of text are needed, this tool can be a great way to get that. It's a good way to test your programming and that the tool being created is working well.Above are a few examples of how the random paragraph generator can be beneficial. The best way to see if this random paragraph picker will be useful for your intended purposes is to give it a try. Generate a number of paragraphs to see if they are beneficial to your current project.If you do find this paragraph tool useful, please do us a favor and let us know how you're using it. It's greatly beneficial for us to know the different ways this tool is being used so we can improve it with updates. This is especially true since there are times when the generators we create get used in completely unanticipated ways from when we initially created them. If you have the time, please send us a quick note on what you'd like to see changed or added to make it better in the future."
        },
        {
            id:null,
            name:"Rediff.com",
            author:"REDIFF STYLE","title":"Chahatt Is A 'Chikni in A Bikini' - Rediff.com",
            description:"A glimpse of a fun sense of travel style.",
            url:"https://www.rediff.com/getahead/report/chahatt-khanna-chikni-in-a-bikini/20230206.htm",
            urlToImage:"https://im.rediff.com/getahead/2023/feb/03fashion1.jpg",
            publishedAt:"2023-02-06T04:04:41Z",
            content:"Chahatt Khanna is something of a globetrotter if her socials are to be believed.\r\nWhen she is in another-day-another-town wardrobe mode, she reaches for pleasing and pretty outfits that are not sacch… [+2076 chars].Can I use these random paragraphs for my project?Yes! All of the random paragraphs in our generator are free to use for your projects.No! All of the paragraphs in the generator are written by humans, not computers. When first building this generator we thought about using computers to generate the paragraphs, but they weren't very good and many times didn't make any sense at all. We therefore took the time to create paragraphs specifically for this generator to make it the best that we could.Can I contribute random paragraphs?Yes. We're always interested in improving this generator and one of the best ways to do that is to add new and interesting paragraphs to the generator. If you'd like to contribute some random paragraphs, please contact us.How many words are there in a paragraph? There are usually about 200 words in a paragraph, but this can vary widely. Most paragraphs focus on a single idea that's expressed with an introductory sentence, then followed by two or more supporting sentences about the idea. A short paragraph may not reach even 50 words while long paragraphs can be over 400 words long, but generally speaking they tend to be approximately 200 words in length."
        },
        
        {
            id:"the-times-of-india",
            name:"The Times of India",
            author:null,
            title:"Is 'Jaane Tu... Ya Jaane Na' actor Imran Khan in LOVE?, gets clicked walking hand-in-hand with Lekha Washington adding fuel to their dating rumours - Indiatimes.com",
            description:"'Jaane Tu... Ya Jaane Na' actor Imran Khan, who has been away from showbiz for quite a long time, made a rare appearance recently. Imran was clicked walking hand in hand with south actress Lekha Washington looking very happy in each other's company and of cou…",
            url:"https://timesofindia.indiatimes.com/videos/entertainment/hindi/is-jaane-tu-ya-jaane-na-actor-imran-khan-in-love-gets-clicked-walking-hand-in-hand-with-lekha-washington-adding-fuel-to-their-dating-rumours/videoshow/97634798.cms",
            urlToImage:"https://timesofindia.indiatimes.com/photo/97634798/size-83760/97634798.jpg",
            publishedAt:"2023-02-06T03:55:23Z",
            content:"'Jaane Tu... Ya Jaane Na' actor Imran Khan\r\n, who has been away from showbiz for quite a long time, made a rare appearance recently. Imran was clicked walking hand in hand with south actress Lekha Wa… [+462 chars].There may be times when you'll want to generate a random list of a particular part of speech rather than all words in general. For example, you may want to create a random list of just nouns. That's exactly what the random noun generator does.A noun is a word that functions as the name of some specific thing, people or place. Nouns are one of the main parts of speech and sentence. They most often occur as the main word in the subject of a clause or the object of a verb. Even if there is no exact agreed upon number of nouns in the English language, a rough calculation suggests there are at least hundreds of thousands of them, and likely more than one million. If we estimate there are approximately 2 million words in the English language, and a look at any dictionary shows approximately 75% of them are nouns, then we can estimate there should be around 1,500,000 nouns in the English language. This goes to show how important nouns are in English and why you may want to create a random list of just them in particular.It's important to note that not all nouns are the same. They can be classified into a number of different categories. Here are some of the type of nouns that exist:"
        },
        
        {
            id:null,
            name:"Tracktollywood.com",
            author:"Sharat","title":"NTR serious on Suma at Amigos pre-release event - TrackTollywood","description":"Kalyan Ram's Amigos pre-release event was held in Hyderabad yesterday and it was a grand success. NTR was the chief guest for the event",
            url:"https://tracktollywood.com/ntr-serious-on-suma-at-amigos-pre-release-event/",
            urlToImage:"https://cdn.123telugu.com/content/wp-content/uploads/2023/02/Amigos-2.jpg",
            publishedAt:"2023-02-06T03:33:21Z",
            content:"Kalyan Ram’s Amigos pre-release event was held in Hyderabad yesterday and it was a grand success. NTR was the chief guest for the event and his presence gave great energy to the movie unit as well as… [+1460 chars]"
        },
        {
            id:null,
            name:"Bollywood Life",
            author:"Nikita Thakkar",
            title:"Bigg Boss 16 winner: Nimrit Kaur Ahluwalia ELIMINATED from Salman Khan's show? Here's what we know - Bollywood Life","description":"Bigg Boss 16: Nimrit Kaur Ahluwalia who had the Ticket to the Finale Week is reportedly out of the race now.",
            url:"https://www.bollywoodlife.com/bigg-boss/bigg-boss-16-winner-nimrit-kaur-ahluwalia-eliminated-from-salman-khans-show-heres-what-we-know-entertainment-news-2330538/",
            urlToImage:"https://st1.bollywoodlife.com/wp-content/uploads/2023/02/Nimrit-24-600x315.png",
            publishedAt:"2023-02-06T03:17:26Z",
            content:"Bigg Boss 16 is simply six days away from its grand finale and it would be heartbreaking for any contestant to get eliminated at this stage. The top six contestants are Nimrit Kaur Ahluwalia, Shiv Th… [+2161 chars]. You have arrived at this webpage in all likelihood because you are in need of some fake words or a fake word generator. If that's the case, you're in exactly the right place. We created the Random Fake Word Generator specifically so you can find a bunch of fake words (sometimes called pseudo words, made up words, or nonsense words). Creating these made-up words is simple. All you need to do is choose the number of fake words you'd like to see and then hit the button. You'll instantly see the results.Fake words are simply made up words that appear to be real, but actually don't exist and don't have any meaning. They initially appear real because they can be pronounced which makes it seem like they would be real words. This leads to the question of why in the world would anyone needs to find fake words or use a fake word generator? It does seem a bit strange at first, but there are actually a number of legitimate reasons why people find this free nonsense word tool useful. Below we list a few of the more common reasons that people might want to generate random pseudo words. If you're in need of some creative inspiration, using nonsense words can be a great way to get the creative juices flowing. Simply generate a fake word and then come up with a definition of what that word could mean. Since it's not a real word, there's no right or wrong answer. You can let your imagination go wild and that should help to get the creative juices flowing. It's a great way to use a made up word generator. Fake words can be an excellent way for writers to begin putting words to paper. Whether they're looking to overcome a bit of writer's block or just need a quality way to begin writing each day, having a random pseudo word generated can be an ideal way to do this. Once the writer has a created a random fake word using the fake word generator, he or she can attempt to write a paragraph about the meaning of that nonsense word, or simply come up with a definition, and then use the word in a sentence. Since the words aren't real, it should help overcome writer's block and help to make it an easy way to begin writing each day."
        },
        {
            id:null,
            name:"Tellybest.com",
            author:null,
            title:"Ghum Hai Kisi Ke Pyaar Mein (GHKKPM) 8th February 2023 Written Update - Tellybest.com","description":"Ghum Hai Kisi Ke Pyaar Mein 8th February 2023 Written Update: GHKKPM written update Today's Ghum Hai Kisi Ke Pyar Mein 8th February 2023 episode starts with Sai thinking of a way to get to Vinayak. She decides to talk to Savi about any information",
            url:"https://www.tellybest.com/written-update/ghum-hai-kisi-ke-pyaar-mein-ghkkpm-8th-february-2023-written-update",
            urlToImage:null,
            publishedAt:"2023-02-06T02:52:33Z",
            content:"Ghum Hai Kisi Ke Pyaar Mein 8th February 2023 Written Update: GHKKPM written update\r\nToday's Ghum Hai Kisi Ke Pyar Mein 8th February 2023 episode starts with Sai thinking of a way to get to Vinayak. … [+1117 chars]If you're in a situation where you need to come up with a name for a project or some other entity, using a fake word generator can be a great way to begin. While none of the random fake words will likely be the exact word you ultimately decide to use, they can be a good beginning point to create the perfect new word for your needs. Generate random nonsense words and begin saying them out loud. This should help you find the sounds you like and it can ultimately help you create the perfect new word for your project. If you and your friends want to be able to tell each other information without anyone else being able to know what you're talking about, creating a set of pseudo words is a great way to do this. You and your friends come up with a definition of each of the fake words and you can say them anytime with anyone listening. While you'll know what you're talking about, nobody else around you will understand the nonsense words coming out of your mouths. You now have secret codewords that you can use at any time!  A wonderful way to improve your gibberish is to find fake words and pronounce them so they easily roll off your tongue. All those nonsense words coming out of your mouth are now your own gibberish language. The more pseudo words and made up words you can use when speaking without hesitation will improve your overall gibberish. This is a skill that every baby you meet will absolutely love! We appreciate you taking the time to use our fake word generator. While we know some of the ways that this tool is being used, if you happen to be using it for another reason not listed above, we'd love to hear from you. We know from experience that the tools we create are sometimes used in ways we never anticipated. When this happens, it helps us a lot to know these unique ways the fake word generator is being used as it can help us make improvements to the tool when we make updates. If you have any ideas or suggestions on how to make this made up word generator more useful, please send us an email to let us know."
        }
    ] )
}
module.exports.apicontroller=get;