const get=(req,res)=>{
    res.send([
        {"source":{"id":null,"name":"Deccan Herald"},"author":null,"title":"VitalFlow Reviews (Prostate) Does VitalFlow Prostate Support Ingredients Really Work? - Deccan Herald","description":"VitalFlow Reviews: New and groundbreaking Report Provides Crucial Information that Every Consumer Should Be Educated. It is imperative to see: Urgent VitalFlow Prostate Report The report reads \"You Are Not Going to Believe What We Discovered!\" CLICK HERE TO B…","url":"https://www.deccanherald.com/brandspot/pr-spot/vitalflow-reviews-prostate-does-vitalflow-prostate-support-ingredients-really-work-1188371.html","urlToImage":"https://www.deccanherald.com/sites/dh/files/p2-1188371-1675678892.png","publishedAt":"2023-02-06T10:21:32Z","content":"VitalFlow Reviews: New and groundbreaking Report Provides Crucial Information that Every Consumer Should Be Educated.\r\nIt is imperative to see: Urgent VitalFlow Prostate Report The report reads \"You … [+24820 chars]"},
        {"source":{"id":null,"name":"Medical Dialogues"},"author":"Rishika Verma","title":"Important Dos And Donts After Kidney Transplant: Dr Vinod Kumar - Medical Dialogues","description":"Important Dos And Donts After Kidney Transplant: Dr Vinod Kumar","url":"https://medicaldialogues.in/photo-stories/important-dos-and-donts-after-kidney-transplant-dr-vinod-kumar-237","urlToImage":"https://medicaldialogues.in/h-upload/2023/02/06/200689-kidney1.jpg","publishedAt":"2023-02-06T10:18:43Z","content":"IMPORTANT DO'S AND DON'TS AFTER KIDNEY TRANSPLANT: DR VINOD KUMAR"},
        {"source":{"id":null,"name":"Deccan Herald"},"author":null,"title":"Primal Grow Pro Reviews (2023) - Deccan Herald","description":"Men who are of African origin have been reported to possess massive penises. There are some experts who claim that Africa contains exotic ingredients that help in the natural development that the penis. African men consume a mixture of substances that increas…","url":"https://www.deccanherald.com/brandspot/pr-spot/primal-grow-pro-reviews-2023-1188366.html","urlToImage":"https://www.deccanherald.com/sites/dh/files/p2-1188366-1675678500.png","publishedAt":"2023-02-06T10:15:00Z","content":"Men who are of African origin have been reported to possess massive penises. There are some experts who claim that Africa contains exotic ingredients that help in the natural development that the pen… [+21861 chars]"},
        {"source":{"id":null,"name":"Punekarnews.in"},"author":"Rahul Dolare","title":"Cervical Cancer: Why women need to be vaccinated - Punekar News","description":"Punekarnews.in is the first and only English language hyper-local news portal of Pune and Pimpri Chinchwad. It was launched in July 2014.","url":"https://www.punekarnews.in/cervical-cancer-why-women-need-to-be-vaccinated/","urlToImage":"https://www.punekarnews.in/wp-content/uploads/2023/02/Rohith-Kumar.jpg","publishedAt":"2023-02-06T10:04:20Z","content":"Dr. Rohit Kumar C, Consultant – Surgical Oncology &amp; Robotic Surgery, HIPEC &amp; PIPAC Specialist, Aster CMI Hospital, Bangalore\r\nPune, 06 Febuary 2023: Cervical cancer is one of the most aggress… [+3907 chars]"},
        {"source":{"id":null,"name":"Expresshealthcare.in"},"author":"EH News Bureau","title":"Karkinos Healthcare and Vinayaka Mission’s Group launches oncology institute in Puducherry - Express Healthcare","description":"The institute aims to address the challenges in cancer care","url":"https://www.expresshealthcare.in/news/karkinos-healthcare-and-vinayaka-missions-group-launches-oncology-institute-in-puducherry/438003/","urlToImage":"https://cdn.expresshealthcare.in/wp-content/uploads/2022/07/05175154/admin-ajax-1.jpg","publishedAt":"2023-02-06T09:47:55Z","content":"The institute aims to address the challenges in cancer care\r\nKarkinos Healthcare and Vinayaka Missions Group including Vinayaka Missions Research Foundation (Deemed to be University) join hands to ad… [+1606 chars]"},
        {"source":{"id":"the-times-of-india","name":"The Times of India"},"author":"ET HealthWorld","title":"WHO releases new breast cancer initiative: Roadmap to save 2.5mn from breast cancer by 2040 - ETHealthWorld","description":"More than 2.3 million cases of breast cancer occur each year, making it the most common cancer among adults. In 95 per cent of countries, breast cancer is the first or second leading cause of female cancer deaths. Yet, survival from breast cancer is widely in…","url":"https://health.economictimes.indiatimes.com/news/industry/who-releases-new-breast-cancer-initiative-roadmap-to-save-2-5mn-from-breast-cancer-by-2040/97644226","urlToImage":"https://etimg.etb2bimg.com/thumb/msid-97644226,imgsize-34796,width-1200,height-628,overlay-ethealthworld/who-releases-new-breast-cancer-initiative-roadmap-to-save-2-5mn-from-breast-cancer-by-2040.jpg","publishedAt":"2023-02-06T09:45:00Z","content":"Geneva: The World Health Organisation (WHO) released a new Global Breast Cancer Initiative Framework providing a roadmap to attain the target to save 2.5 million lives from breast cancer by 2040. The… [+3799 chars]"},
        {"source":{"id":null,"name":"Financial Express"},"author":null,"title":"This device can detect brain tumour from urine sample - The Financial Express","description":null,"url":"https://www.financialexpress.com/lifestyle/health/this-device-can-detect-brain-tumour-from-urine-sample/2972528/","urlToImage":'https://cdn-prod.medicalnewstoday.com/content/images/articles/321/321809/illustration-of-brain-tumor.jpg',"publishedAt":"2023-02-06T07:20:26Z","content":null},
        {"source":{"id":null,"name":"THE WEEK"},"author":"PTI","title":"AI could help deliver personalised cancer treatments: Study - The Week","description":"Researchers have leveraged artificial intelligence (AI) technology to identify genes critical to a cancer cell's survival, and could help deliver personalised cancer patient treatments, according to a new study.","url":"https://www.theweek.in/news/health/2023/02/06/ai-could-help-deliver-personalised-cancer-treatments--study.html","urlToImage":"https://www.theweek.in/content/dam/week/news/2022/images/2022/12/21/diagnosis--artificial-intelligence-AI-healthcare-Doctor-heart-computer-shut.jpg","publishedAt":"2023-02-06T06:48:00Z","content":"Researchers have leveraged artificial intelligence (AI) technology to identify genes critical to a cancer cell's survival, and could help deliver personalised cancer patient treatments, according to … [+2489 chars]"}
        ,{"source":{"id":null,"name":"Hindustan Times"},"author":"ANI","title":"Preventative measures for optic nerve hypoplasia: Research - Hindustan Times","description":"According to the National Institutes of Health, the disorder arises when the optic nerves that convey information from the retina to the brain are undeveloped at birth, resulting in moderate to severe vision loss in children (NIH). | Health","url":"https://www.hindustantimes.com/lifestyle/health/preventative-measures-for-optic-nerve-hypoplasia-research-101675665258176.html","urlToImage":"https://images.hindustantimes.com/img/2023/02/06/1600x900/_3dc97fce-437f-11eb-9d7d-764df83b7a87_1675665691778_1675665691778.jpg","publishedAt":"2023-02-06T07:21:37Z","content":"Researchers at VTC's Fralin Biomedical Research Institute are investigating potential preventative and treatment methods for optic nerve hypoplasia (ONH), a disorder that causes vision impairment in … [+1752 chars]"}
    
    
        
    ] )
}
module.exports.apicontroller=get;