const get=(req,res)=>{
    res.send([
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Catherine Shu","title":"The solo GP behind iSeed SEA launches his second fund for Southeast Asia","description":"If you follow Southeast Asia funding, you’re probably familiar with iSeed SEA. Some of the startups the fund has invested in since it launched in 2020 include Dat Bike, Skuad and Upmesh. What you might not know, however, is that iSeed SEA is a solo GP fund. N…","url":"https://techcrunch.com/2023/02/05/wing-vasiksiri/","urlToImage":"https://techcrunch.com/wp-content/uploads/2023/02/headshot.jpg?resize=1200,775","publishedAt":"2023-02-06T04:35:52Z","content":"If you follow Southeast Asia funding, youre probably familiar with iSeed SEA. Some of the startups the fund has invested in since it launched in 2020 include Dat Bike, Skuad and Upmesh. What you migh… [+5951 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Mike Butcher","title":"Post Series-B, anti-fraud platform SEON acquires AML startup Complytron for a rumoured €2.5M","description":"Budapest-based SEON, — an anti-fraud platform which looks at a customer’s ‘digital footprint’ to weed out false accounts and thus prevent fraudulent transactions —  has acquired compliance and AML specialist firm,  Complytron, also based out of Budapest.","url":"https://techcrunch.com/2023/02/05/post-series-b-anti-fraud-platform-seon-acquires-aml-startup-complytron-for-a-rumoured-e2-5m/","urlToImage":"https://techcrunch.com/wp-content/uploads/2023/02/SEON.jpeg?resize=1200,675","publishedAt":"2023-02-05T20:25:22Z","content":"Budapest-based SEON, an anti-fraud platform which looks at a customers digital footprint to weed out false accounts and thus prevent fraudulent transactions   has acquired compliance and AML speciali… [+2026 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Manish Singh","title":"India is blocking over 230 betting and loan apps, many with ties to China","description":"India is moving to block 232 betting and loan apps, many of which have ties to China, in the latest crackdown.","url":"https://techcrunch.com/2023/02/05/india-is-blocking-over-230-betting-and-loan-apps-many-with-ties-to-china/","urlToImage":"https://techcrunch.com/wp-content/uploads/2022/07/GettyImages-923835828.jpg?resize=1200,750","publishedAt":"2023-02-05T10:19:55Z","content":"India is moving to block 232 apps, some with links to China, that offer betting and loan services in the South Asian market to prevent misuse of the citizens data, the state-owned public broadcaster … [+2547 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Ivan Mehta","title":"Elon Musk says Twitter will provide a free write-only API to bots providing 'good' content","description":"Elon Musk said that due to feedback Twitter will provide a write-only API for \"bots providing good content that is free.\"","url":"https://techcrunch.com/2023/02/04/elon-musk-says-twitter-will-provide-a-free-write-only-api-to-bots-providing-good-content/","urlToImage":"https://techcrunch.com/wp-content/uploads/2022/10/rainbow-twitter-birds-1.jpg?resize=1200,645","publishedAt":"2023-02-05T06:51:47Z","content":"Last week, Twitter said it is shutting down free access to its APIs starting February 9. Now, days before the deadline, Elon Musk said that due to feedback Twitter will provide a write-only API for “… [+2458 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Haje Jan Kamps","title":"Startups, here's how you can make hardware without ruining the planet","description":"If you can't make planet-friendly choices as the founder of a startup, when the buck literally stops with you, when can you?","url":"https://techcrunch.com/2023/02/05/sustainable-hardware-startups/","urlToImage":"https://techcrunch.com/wp-content/uploads/2018/07/Labelbox-AI-training-data-software.png?resize=1200,638","publishedAt":"2023-02-04T17:51:14Z","content":"Nobody starts a hardware company with the express goal of destroying as much of the planet as they possibly can. Walking around the startup hall at CES, however, I noticed that with a few notable exc… [+3629 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Sarah Perez","title":"This Week in Apps: Instagram's founders' new app, another Twitter rival, Biden admin criticizes app stores","description":"This Week in Apps offers a way to keep up with the latest from the world of apps, including news, updates, startup fundings, M&As and much more.","url":"https://techcrunch.com/2023/02/04/this-week-in-apps-instagrams-founders-new-app-another-twitter-rival-biden-admin-criticizes-app-stores/","urlToImage":"https://techcrunch.com/wp-content/uploads/2022/07/this-week-in-apps-splash-2022.webp?resize=1200,637","publishedAt":"2023-02-04T01:34:06Z","content":"Welcome back to This Week in Apps, the weekly TechCrunch series that recaps the latest in mobile OS news, mobile applications and the overall app economy.\r\nThe app economy in 2023 hit a few snags, as… [+19485 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Henry Pickavet","title":"Netflix crackdown, monetizing ChatGPT and bypassing FB’s 2FA","description":"Happy weekend, folks, and welcome back to the TechCrunch Week in Review. Let's check out just a few of the top stories from the week.","url":"https://techcrunch.com/2023/02/04/netflix-crackdown-monetizing-chatgpt-and-bypassing-fbs-2fa/","urlToImage":"https://techcrunch.com/wp-content/uploads/2022/07/photo-1643208589889-0735ad7218f0-e1658176963387.jpeg","publishedAt":"2023-02-04T01:07:32Z","content":"Happy weekend, folks, and welcome back to the TechCrunch Week in Review. Henry here, standing in for a vacationing Kyle Wiggers, who is standing in for a parental-leaving Greg Kumparak. Listen, weve … [+3793 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Natasha Mascarenhas","title":"Dear founders, returning to the office is a numbers game","description":"Let's talk about the data behind return to office, noisy venture firms, Salesforce spinouts and Artifacts on facts.","url":"https://techcrunch.com/2023/02/04/2023-is-the-year-of-the-bottom-line/","urlToImage":"https://techcrunch.com/wp-content/uploads/2022/06/modsy-empty-chair.jpg?resize=1200,675","publishedAt":"2023-02-03T22:53:55Z","content":"Welcome to Startups Weekly, a nuanced take on this weeks startup news and trends by Senior Reporter and Equity co-host Natasha Mascarenhas. To get this in your inbox, subscribe here.\r\nToward the end … [+5329 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Anna Heim","title":"Does usage-based pricing call for a new growth infrastructure stack?","description":"'It's not either usage-based or subscription pricing,' VC firm OpenView wrote in a report. These hybrid approaches call for new tools, but which ones?","url":"https://techcrunch.com/2023/02/04/does-usage-based-pricing-call-for-a-new-growth-infrastructure-stack/","urlToImage":"https://techcrunch.com/wp-content/uploads/2020/06/NSussman_Techcrunch_Exchange-multicolor.jpg?resize=1200,900","publishedAt":"2023-02-03T21:06:25Z","content":"W\r\nelcome to the TechCrunch Exchange, a weekly startups-and-markets newsletter. Its inspired by the daily TechCrunch+ column where it gets its name. Want it in your inbox every Saturday? Sign up here… [+1023 chars]"},
        {"source":{"id":"techcrunch","name":"TechCrunch"},"author":"Romain Dillet","title":"Ovni Capital is a new French VC firm backing startups with global ambitions","description":"If you’re a French entrepreneur, there’s a new venture capital firm in town. Ovni Capital is announcing a first closing of €50 million ($54 million at today’s exchange rate) for its early-stage fund. The firm’s two general partners Arnaud Laurent and Augustin…","url":"https://techcrunch.com/2023/02/05/ovni-capital-is-a-new-french-vc-firm-backing-startups-with-global-ambitions/","urlToImage":"https://techcrunch.com/wp-content/uploads/2023/02/Ovni-Capital.jpg?resize=1200,800","publishedAt":"2023-02-03T17:40:55Z","content":"If youre a French entrepreneur, theres a new venture capital firm in town. Ovni Capital is announcing a first closing of 50 million ($54 million at todays exchange rate) for its early-stage fund.\r\nTh… [+1975 chars]"}
    
    
        
    ] )
}
module.exports.apicontroller=get;