const get=(req,res)=>{
    res.send([
        {"source":{"id":"cnn","name":"CNN"},"author":"Nouran Salahieh","title":"More than 400 products including breakfast sandwiches and fruit cups recalled due to possible Listeria contamination - CNN","description":"More than 400 food products sold under dozens of brand names were recalled due to possible Listeria contamination, the US Food and Drug Administration announced Friday.","url":"https://www.cnn.com/2023/02/06/health/fresh-ideation-food-group-recall-listeria-contamination/index.html","urlToImage":"https://media.cnn.com/api/v1/images/stellar/prod/230206003310-breakfast-sandwiches-stock.jpg?c=16x9&q=w_800,c_fill","publishedAt":"2023-02-06T08:25:00Z","content":"More than 400 food products sold under dozens of brand names were recalled due to possible Listeria contamination, the US Food and Drug Administration announced Friday.\r\nThe recall by Fresh Ideation … [+1601 chars]"},
        {"source":{"id":null,"name":"OilPrice.com"},"author":"Irina Slav","title":"Goldman Sachs Warns Of An Imminent Oil Supply Shortage - OilPrice.com","description":"Goldman Sachs believes an oil supply shortage is looming due to underinvestment, with oil prices set to break $100","url":"https://oilprice.com/Latest-Energy-News/World-News/Goldman-Sachs-Warns-Of-An-Imminent-Oil-Supply-Shortage.html","urlToImage":"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8YnVpbGRpbmd8ZW58MHx8MHx8&w=1000&q=80","publishedAt":"2023-02-06T07:22:21Z","content":"The UKs nuclear power industry…\r\nThe recent 25-point rate hike…\r\nBy Irina Slav - Feb 06, 2023, 1:22 AM CSTCrude oil could soon swing into a deficit that will make next year a difficult one, Goldman S… [+1775 chars]"},
        {"source":{"id":null,"name":"Fox Business"},"author":"Megan Henney","title":"US economy could see 'second chapter' in pandemic price surge - Fox Business","description":"Another inflation spike could take hold in the U.S. economy as a result of China reopening its economy from COVID-19 lockdowns, according to one analyst.","url":"https://www.foxbusiness.com/economy/us-economy-could-see-second-chapter-pandemic-price-surge","urlToImage":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr7eZyh-i9FIZeccxsmj4iia2PUQLtwTcyQg&usqp=CAU","publishedAt":"2023-02-06T07:06:29Z","content":"The new year brought with it hope that a long, painful season of high inflation was finally coming to a close – but the U.S. economy may not be out of the woods yet. \r\nIn a note to clients last week,… [+3588 chars]"}
    
        
    ] )
}
module.exports.apicontroller=get;