const get=(req,res)=>{
    res.send([
        {
            "id": "1",
            "name": "Business Standard",
            "author": "BS Web Team",
            "title": "Apple updating ad, search features to separate OS from Google: Report - Business Standard",
            "description": "Earlier this month Apple announced Business Connect which allows companies to claim their legal location and interact with customers",
            "url": "https://www.business-standard.com/article/companies/apple-updating-ad-search-features-to-separate-os-from-alphabet-report-123012500437_1.html",
            "urlToImage": "https://bsmedia.business-standard.com/_media/bs/img/article/2022-10/19/full/1666149541-049.jpg",
            "publishedAt": "2023-01-25T06:32:00Z",
            "content": "In a bid to separate its mobile operating system from Google's parent Alphabet, Apple is taking steps to update its maps, search feature and advertising, a report by the Financial Times said. Technology is something that is gaining increasing importance in the world today. Wherever you look, there is technology. Even the device you are using to read this article uses technology. In simple words, technology is when we use science to apply it for practical purposesFor example, in a mobile phone, which is a form of technology, we are taking the practical purpose of communication and mixing it with science to create a phone. Here are some paragraphs on technology for children and students.Technology is a very amazing thing that scientists create. Scientists look at all the things that we as human beings will need in our lives, then make a cool gadget or object. For example, scientists knew that we needed a way to communicate with each other even when we are not together. Because of this, they created a telephone which we can use to talk to other people even when we are not with themTechnology is all around you – in your gaming gadgets like the Wii, Playstation, Xbox, etc. and in your mobile phones, iPads, computers, etc. Most of the things we have in our kitchen, like the microwave, toaster, fridge, etc. are all different types of technology. Technology is when we take something from the world of science and then create it into something that humans use. "
        },
        {
            "id": "2",
            "name": "Google News",
            "author": "MADHU BALAJI",
            "title": "Google Messages could soon let users create their profiles - BusinessLine",
            "description": "Google Messages will let users set profile with photo, name and email address.",
            "url": "https://news.google.com/__i/rss/rd/articles/CBMifWh0dHBzOi8vd3d3LnRoZWhpbmR1YnVzaW5lc3NsaW5lLmNvbS9pbmZvLXRlY2gvZ29vZ2xlLW1lc3NhZ2VzLWNvdWxkLXNvb24tbGV0LXVzZXJzLWNyZWF0ZS10aGVpci1wcm9maWxlcy9hcnRpY2xlNjY0MzA5NTIuZWNl0gGCAWh0dHBzOi8vd3d3LnRoZWhpbmR1YnVzaW5lc3NsaW5lLmNvbS9pbmZvLXRlY2gvZ29vZ2xlLW1lc3NhZ2VzLWNvdWxkLXNvb24tbGV0LXVzZXJzLWNyZWF0ZS10aGVpci1wcm9maWxlcy9hcnRpY2xlNjY0MzA5NTIuZWNlL2FtcC8?oc=5",
            "urlToImage": "https://bl-i.thgim.com/public/incoming/nlr2gh/article66355711.ece/alternates/FREE_1200/Google.JPG",
            "publishedAt": "2023-01-25T06:27:47Z",
            "content": `A screenshot shared by a Reddit user u/seeareeff and discovered by Esper’s Mishaal Rahman revealed. As per reports, the page was found.Technology is all around you – in your gaming gadgets like the Wii, Playstation, Xbox, etc. and in your mobile phones, iPads, computers, etc. Most of the things we have in our kitchen, like the microwave, toaster, fridge, etc. are all different types of technology. Technology is when we take something from the world of science and then create it into something that humans use.We must keep our food cold so that it is not spoilt by being out in the warm weather. This concept of science helped scientists develop technology to keep our food cold when we are not eating it by using the fridge. However, all of us like to eat hot food. So, to instantly make food hot, scientists created a microwave. In this way, scientists used technology to help all of us with our daily lives. Technology is very useful in our daily lives.When we look around us, we see a huge number of examples of technology. The mobile phone in our hands, the headphones we wear for listening to music, the microwave we use to heat our food, and even the construction of the buildings we live in – all use some or the other type of technology.Technology is so important in today’s world that it is almost impossible to imagine a life without it. Could you imagine what you would do if you weren’t able to watch television every once? Or what would you do if you were unable to talk to your grandmother who lives away from you on the phone`
        },
        {
            "id": "3",
            "name": "Sportskeeda",
            "author": "Spencer Whitworth",
            "title": "What are smithing templates in Minecraft snapshot 23w04a? - Sportskeeda",
            "description": "Minecraft's 1.20 update may still be quite some time away, but fortunately, the preview snapshots give players some insight into what's to come.",
            "url": "https://www.sportskeeda.com/minecraft/what-smithing-templates-minecraft-snapshot-23w04a",
            "urlToImage": "https://staticg.sportskeeda.com/editor/2023/01/4fe0b-16746206210581-1920.jpg",
            "publishedAt": "2023-01-25T06:04:42Z",
            "content": `Minecraft's 1.20 update may still be quite some time away, but fortunately, the preview snapshots give players some insight into what's to come. Java Edition snapshot 23w04a was recently released,Not having technology in our lives would make us feel like something in our lives is missing. Yes, that’s how big a role technology plays in our lives if we think deeply about it.One of the best and most accessible forms of technology is the mobile phone or, more precisely, the smartphone. A smartphone is a phone which can connect to the internet. They have many advanced features in a phone and are a very good example of technology.Technology is the most useful form of science for the general population. In simple words, technology is when we take the concepts of science and transform them into gadgets and devices that are useful to us as human beings. When we look around us, almost everything is a result of or a form of technology.For example, the device you are using right now is a form of technology made for communication, or the refrigerator in your kitchen is a use of science that helps to keep your food fresh and cool. With these examples, we see how dependent we are on technology and how important it is for us in our daily lives.It isn’t easy to imagine our lives without using any form of technology. For the smallest of communications, we tend to turn to our mobile phones. Even most of the food we eat is packaged in factories using various technologies. Thus, imagining a life without technology is impossible. It is not only a fact of life but also a necessity for all of us.`
        },
        {
            "id": "4",
            "name": "Jagran.com",
            "author": "Ashish Singh",
            "title": "Flipkart Republic Day Sale 2023: Get Massive Discounts On THESE Mid-Range Smartphones - Jagran English",
            "description": "Flipkart Republic Day Sale 2023: Get steal deals on mid-range smartphones on Flipkart till January 31.",
            "url": "https://english.jagran.com/technology/flipkart-republic-day-sale-2023-get-massive-discounts-on-these-midrange-smartphones-10062406",
            "urlToImage": "https://thumbs.dreamstime.com/b/internet-information-technology-concept-laptop-computer-showing-data-processing-screen-122397310.jpg",
            "publishedAt": "2023-01-25T06:02:30Z",
            "content": `Republic Day 2023 is near, and there are numerous sales going on Flipkart. If you are looking to buy a smartphone,Interesting smartphone with an AMOLED display on offer with a 64 MP primary shooter along with the 8 MP and 2 MP camera sensors paired with the 16 MP front camera for selfies and video calls.In fact, the smartphone, that is, a mobile phone which can connect to the internet, is becoming one of the fastest-growing and most accessible forms of technology around the world. On a smartphone, you can click photographs, browse the internet, listen to music, and use social media. With the advent of smartphone technology, the practical purpose of not only communicating with your friends is met, but also so many others, as mentioned.Thus, in today’s world, the importance of technology becomes more and more as the years pass. Scientists have done so much to advance humans using technology, and we still have a long way to go.Technology refers to when a concept of science is used to create something that serves a practical purpose in human life. For example, the telephone helps two people to talk to each other even when they are not physically together.Technology is very important simply because it helps to make our lives much easier and comfortable. For example, walking around to different places can be very tiring. Hence, our lives are made easier by using a car to get to places rather than by walking.`
        },
        {
            "id": "5",
            "name": "Sportskeeda",
            "author": "Arhaan Raje",
            "title": "Why do rappers like NBA Lil Pap and NBA YoungBoy use the NBA prefix in their name? - Sportskeeda",
            "description": "Rappers NBA YoungBoy and his former associate, NBA LilPap, have gained massive popularity among league circles.",
            "url": "https://www.sportskeeda.com/basketball/why-rappers-like-nba-lil-pap-nba-youngboy-use-nba-prefix-name",
            "urlToImage": "https://staticc.sportskeeda.com/editor/2023/01/85c62-16746239998242-1920.jpg",
            "publishedAt": "2023-01-25T05:19:00Z",
            "content": `Rappers NBA YoungBoy and his former associate, NBA LilPap, have gained massive popularity among league circles. Their work has obviously had more to do with their recognition, but the prefix "NBA" He got held in juvenile detention, where he worked on his music, writing lyrics for his debut projects.Technology is the exploration of scientific knowledge to develop tools and techniques to transform the world by improving efficiency in almost everything we do. With every new technological invention, it is dramatically changing the society and the environment. Today, it has become unimaginable to be in a world without technology.

            You will find below a number of short paragraphs on the topic Technology of varying word lengths. We hope these paragraphs on Technology will help students in completing their school assignments. These will also help children write and read out paragraphs in simple words and with small sentences. Students can select any Technology paragraph according to their particular requirement.Technology is a necessity of the modern lifestyle. Every day there are new ideas and advancements in the technology as the world becomes more involved in discovering and utilizing the potential of natural resources. Technology has improved human lives significantly by providing convenience and efficiency. It has made easily possible for us to access education, communication, medicine, transportation, sports, etc.

            In this fast pace and ever-changing world, technological innovations take no time in becoming obsolete. However, today for any nation’s development technology plays a vital role in improving its economy and the lives of the people. Technology is the present and future of this era. `
        },
        {
            "id": "6",
            "name": "The Times of India",
            "author": "TIMESOFINDIA",
            "title": "Garena Free Fire Max Redeem Codes for January 25: Grab premium bundles, loot crates and more - Times of India",
            "description": "The developers of the game are always incorporating new alphanumeric codes into it. Players can win complimentary prizes by using these codes. These c",
            "url": "https://timesofindia.indiatimes.com/gadgets-news/garena-free-fire-max-redeem-codes-for-january-25-grab-premium-bundles-loot-crates-and-more/articleshow/97298228.cms",
            "urlToImage": "https://static.toiimg.com/thumb/msid-97298205,width-1070,height-580,imgsize-54828,resizemode-75,overlay-toi_sw,pt-32,y_pad-40/photo.jpg",
            "publishedAt": "2023-01-25T05:01:00Z",
            "content": `China approves 88 games in January, including titles by Tencent and NetEaseShenzhen-based Tencent, the world's largest gaming company, received at least one game licence for a mobile game named  Garena Free Fire is among the apps and games that the Indian government has forbidden.Starting from smart phones to wake you up, fitness bands to keep you fit, to the computers you work upon and the electricity you use – everything is the whimsical world of technology. The technological innovations like internet and smart phones have made possible for people to connect with others all over the globe, get information about any nook and corner of the world, create a digital and a global economy, seek entertainment and the list continues. Human lives are so intricately connected to technology that they just cannot function without it. Today, every nation is thriving on technology to generate economy, employment all leading towards a smart lifestyle. Technology has so much to offer and everyday its potential is tested to new limits. However, with technologies like artificial intelligence, nuclear weapons are a threat not only to the environment but mankind also and their scale of mass destruction and damage cannot be imagined.Technology has evolved remarkably over the past few decades. The beginning of modern technology could be seen in early 1800s – the start of industrial revolution and since then there has been no looking back.
            Gone are the days of waiting for months to receive a letter from your friend or relative residing in a distant place. At the click of some buttons you can talk to anyone sitting in a remote part of the world. Earlier people used to flock to library for research work or pleasure reading which has now been replaced with e books and search engines.`
        },
        {
            "id": "7",
            "name": "Samsung.com",
            "author": "Samsung",
            "title": "Sneak Peek Into The Art World With Samsung Lifestyle TV, The Frame & The Upside Space - Samsung Newsroom India",
            "description": "Digital medium is enabling artists to present their art in a more immersive and accessible way. Display technology, including televisions, serves as a great",
            "url": "https://news.samsung.com/in/sneak-peek-into-the-art-world-with-samsung-lifestyle-tv-the-frame-the-upside-space",
            "urlToImage": "https://img.global.news.samsung.com/in/wp-content/uploads/2023/01/FEATURE-LISA-1.jpg",
            "publishedAt": "2023-01-25T04:45:15Z",
            "content": "Digital medium is enabling artists to present their art in a more immersive and accessible way. Display technology, including televisions, serves as a great platform for experiencing artistic express… [+2873 chars].Some 100 years back, people could not predict the incoming hurricane, its position and time of attack but now anyone with a mobile phone can find these details and interpret it accurately. The outdoor activities have now been replaced with computers and Play Station. Now a days, kids prefer spending time on what their virtual friends are up to rather than spending quality time with their family or friends.Technology is advancing with a speed of light making it difficult to cope up with. It has transformed our lives and has turned the world into a global village. Its potential is limitless and awaits great discoveries in the near future.Mankind has used technology to explore and discover the mysteries of nature and its existence. In that quest, technology has also managed to bring luxuries and comfort to our daily lives. Technology has helped scientists to peek into the dark space, explore the world of gadgets, test the powers of nuclear energy and discover the undiscovered.Everyday scientists are exploring ways to exploit solar energy, wind energy and harnessing power from it, converting salty ocean water to pure fresh water, predicting climatic conditions and much more. New technologies are coming up to intricately study the lives of different species whom we know very little about. Technological efforts are being made to preserve endanger species and produce better and healthy crops by genetically modifying them."
        },
        {
            "id": "8",
            "name": "Google News",
            "author": "Tech Desk",
            "title": "WhatsApp’s new macOS beta app now available for download: Here’s what is new - The Indian Express",
            "description": "The new native WhatsApp app on macOS runs on systems powered by the M1 silicon and some Intel-powered Macs which can run apps built using Mac Catalyst.",
            "url": "https://news.google.com/__i/rss/rd/articles/CBMihQFodHRwczovL2luZGlhbmV4cHJlc3MuY29tL2FydGljbGUvdGVjaG5vbG9neS93aGF0c2FwcC1tYWNvcy1hcHAtcHVibGljLWJldGEtbm93LWF2YWlsYWJsZS1mb3ItZG93bmxvYWQtZnJvbS1vZmZpY2lhbC13ZWJzaXRlLTg0MDMwMDUv0gGKAWh0dHBzOi8vaW5kaWFuZXhwcmVzcy5jb20vYXJ0aWNsZS90ZWNobm9sb2d5L3doYXRzYXBwLW1hY29zLWFwcC1wdWJsaWMtYmV0YS1ub3ctYXZhaWxhYmxlLWZvci1kb3dubG9hZC1mcm9tLW9mZmljaWFsLXdlYnNpdGUtODQwMzAwNS9saXRlLw?oc=5",
            "urlToImage": "https://images.indianexpress.com/2023/01/WhatsApp-Express-Photo-1.jpg",
            "publishedAt": "2023-01-25T04:23:30Z",
            "content": "WhatsApp’s new native app for macOS– which is built using Mac Catalyst– appears to Technogy.However, technology can become a reason for self-destruction if not used decisively. Thus, it becomes very important to strike a balance between technology and nature, as technology knows no limit and can turn disparaging. A lot of E-waste is generated because of the excessive use of smart phones, televisions and so many other electronics.These E-wastes are getting dumped onto fields polluting the land and a lot of natural resources are wasted. Nuclear energy and biological warfare are a threat to the nature as it has long lasting and destructive effects to the environment. Manufacturing of modern day technologies, cars and industries have resulted in air, water and land pollution which has resulted in alarming situations of climate change and global warming.The 21st century is empowered with gifts of technology like internet, smart phones, super-fast computers, smart televisions, artificial intelligence (robots), etc. Today the world is envisioning the future as some kind of a science fiction movie – a world of incredible technology. It has become a part and parcel of everyone’s daily routine and has revolutionized their lives in unimaginable ways. It has made possible to access any information just at the press of the key!Technology has aided in the evolution of the modern world and how we imagine it. The technological innovations have made the lives of human beings convenient, easy and better than what it was yesterday. It has made possible for people to connect from all over the world through smart phones, emails, video calls, etc."
        },
        {
            "id": "1",
            "name": "Business Standard",
            "author": "BS Web Team",
            "title": "Apple updating ad, search features to separate OS from Google: Report - Business Standard",
            "description": "Earlier this month Apple announced Business Connect which allows companies to claim their legal location and interact with customers",
            "url": "https://www.business-standard.com/article/companies/apple-updating-ad-search-features-to-separate-os-from-alphabet-report-123012500437_1.html",
            "urlToImage": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRFiwUdU8uncjTj38-kgJHfr4uZZrjIZhsJ-pw8axr&s",
            "publishedAt": "2023-01-25T06:32:00Z",
            "content": "In a bid to separate its mobile operating system from Google's parent Alphabet, Apple is taking steps to update its maps, search feature and advertising, a report by the Financial Times said.Technology has replaced the conventional modes of transportation to faster and convenient ways like metros and airplanes. Medical innovations to cure diseases and rectify them so easily would not have been possible without technological innovations like MRI scans, surgical machineries and other advanced techniques. Technology has now become one of the most integral parts in the development of any nation.As we know, nothing interesting is ever completely one-sided there are downsides to the technology as well. It has brought a vicious cycle of cyber warfare, hackers, terrorist attacks, social stress and lot more. It has made people addicted to social networking sites, making them lethargic and ignorant. Modern technology is eliminating the creativity of human hands and brain.Technology has certainly paved ways for a better lifestyle, but it has also caused damage and destruction to the environment. Despite of its various consequences, technology is here to stay and there is no escaping it. Technology is a tool to be used with rationality. Hence, it is upon the user to decide its potential.Since the invention of computers and calculators, technology has transformed the dynamics of education. With the increasing popularity of internet and its powers, online search engines have opened the doorways of accessing any information just by the press of a key. Bringing technology to classrooms by introducing smart boards, and projectors that screen digital simulations and models helps teachers to explain concepts with such ease and also helps students grasp faster and better. It helps students connect at a global level. Technology has also made the system of assessment easier and efficient. However, there are no less cases where technology has hindered student’s ability to learn and served more as a distraction than a way of learning. "
        },
    

    ] )
}
module.exports.apicontroller=get;